project:
  type: website
  output-dir: docs

website:
  title: "Data-Driven Transport Planning"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: prerequisites.qmd
        text: Prerequisites
      - href: exercises/index.qmd
        text: Exercises

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
