project:
  type: website
  output-dir: docs

website:
  title: "Data-Driven Transport Planning"
  site-url: "https://pctni.github.io/hack/"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: ideas.qmd
        text: Ideas
      - href: examples.qmd
        text: Examples
      - href: prerequisites.qmd
        text: Prerequisites
      - href: exercises/index.qmd
        text: Exercises

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
